version: '3'
services:
  app:
    build: .
    ports:
      - '80:80'
    command: yarn start
    environment:
      - NODE_ENV=production
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
